[package]
name = "web"
version = "0.1.0"
authors = ["Tomás Farías Santana <tomas@tomasfarias.dev>"]
edition = "2018"

[dependencies]
actix-web = "3"
actix-files = "0.3"

env_logger = "^0.7"
tera = "^1.5.0"