version: '3'
services:
  db:
    image: postgres:13-alpine
    env_file:
      - db.env
    ports:
      - "5432"
  web:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    env_file:
      - web.env
    ports:
      - "8080"
